export default class ClientGameProt {
    static all: ClientGameProt[] = [];
    static byId: ClientGameProt[] = [];

    static readonly NO_TIMEOUT = new ClientGameProt(6, 107, 0); // NXT naming

    static readonly IDLE_TIMER = new ClientGameProt(30, 146, 0);

    static readonly EVENT_TRACKING = new ClientGameProt(34, 217, -2);

    // autogenerated as part of obfuscation process
    static readonly ANTICHEAT_OPLOGIC1 = new ClientGameProt(60, 47, 4);
    static readonly ANTICHEAT_OPLOGIC2 = new ClientGameProt(61, 218, 4);
    static readonly ANTICHEAT_OPLOGIC3 = new ClientGameProt(62, 37, 3);
    static readonly ANTICHEAT_OPLOGIC4 = new ClientGameProt(63, 34, 2);
    static readonly ANTICHEAT_OPLOGIC5 = new ClientGameProt(64, 7, 0);
    static readonly ANTICHEAT_OPLOGIC6 = new ClientGameProt(65, 177, 4);
    static readonly ANTICHEAT_OPLOGIC7 = new ClientGameProt(66, 50, 4);
    static readonly ANTICHEAT_OPLOGIC8 = new ClientGameProt(67, 100, 2);
    static readonly ANTICHEAT_OPLOGIC9 = new ClientGameProt(68, 169, 1);

    // autogenerated as part of obfuscation process
    static readonly ANTICHEAT_CYCLELOGIC1 = new ClientGameProt(70, 46, 1);
    static readonly ANTICHEAT_CYCLELOGIC2 = new ClientGameProt(71, 148, -1);
    static readonly ANTICHEAT_CYCLELOGIC3 = new ClientGameProt(74, 144, 3);
    static readonly ANTICHEAT_CYCLELOGIC4 = new ClientGameProt(72, 41, 4);
    static readonly ANTICHEAT_CYCLELOGIC5 = new ClientGameProt(75, 232, 0);
    static readonly ANTICHEAT_CYCLELOGIC6 = new ClientGameProt(73, 215, -1);

    static readonly OPOBJ1 = new ClientGameProt(80, 231, 6); // NXT naming
    static readonly OPOBJ2 = new ClientGameProt(81, 110, 6); // NXT naming
    static readonly OPOBJ3 = new ClientGameProt(82, 27, 6); // NXT naming
    static readonly OPOBJ4 = new ClientGameProt(83, 17, 6); // NXT naming
    static readonly OPOBJ5 = new ClientGameProt(84, 225, 6); // NXT naming
    static readonly OPOBJT = new ClientGameProt(88, 25, 8); // NXT naming
    static readonly OPOBJU = new ClientGameProt(89, 111, 12); // NXT naming

    static readonly OPNPC1 = new ClientGameProt(100, 222, 2); // NXT naming
    static readonly OPNPC2 = new ClientGameProt(101, 84, 2); // NXT naming
    static readonly OPNPC3 = new ClientGameProt(102, 132, 2); // NXT naming
    static readonly OPNPC4 = new ClientGameProt(103, 229, 2); // NXT naming
    static readonly OPNPC5 = new ClientGameProt(104, 102, 2); // NXT naming
    static readonly OPNPCT = new ClientGameProt(108, 101, 4); // NXT naming
    static readonly OPNPCU = new ClientGameProt(109, 52, 8); // NXT naming

    static readonly OPLOC1 = new ClientGameProt(120, 238, 6); // NXT naming
    static readonly OPLOC2 = new ClientGameProt(121, 38, 6); // NXT naming
    static readonly OPLOC3 = new ClientGameProt(122, 19, 6); // NXT naming
    static readonly OPLOC4 = new ClientGameProt(123, 55, 6); // NXT naming
    static readonly OPLOC5 = new ClientGameProt(124, 243, 6); // NXT naming
    static readonly OPLOCT = new ClientGameProt(128, 182, 8); // NXT naming
    static readonly OPLOCU = new ClientGameProt(129, 106, 12); // NXT naming

    static readonly OPPLAYER1 = new ClientGameProt(140, 211, 2); // NXT naming
    static readonly OPPLAYER2 = new ClientGameProt(141, 219, 2); // NXT naming
    static readonly OPPLAYER3 = new ClientGameProt(142, 64, 2); // NXT naming
    static readonly OPPLAYER4 = new ClientGameProt(143, 43, 2); // NXT naming
    static readonly OPPLAYERT = new ClientGameProt(148, 73, 4); // NXT naming
    static readonly OPPLAYERU = new ClientGameProt(149, 48, 8); // NXT naming

    static readonly OPHELD1 = new ClientGameProt(160, 228, 6); // name based on runescript trigger
    static readonly OPHELD2 = new ClientGameProt(161, 166, 6); // name based on runescript trigger
    static readonly OPHELD3 = new ClientGameProt(162, 221, 6); // name based on runescript trigger
    static readonly OPHELD4 = new ClientGameProt(163, 6, 6); // name based on runescript trigger
    static readonly OPHELD5 = new ClientGameProt(164, 133, 6); // name based on runescript trigger
    static readonly OPHELDT = new ClientGameProt(168, 143, 8); // name based on runescript trigger
    static readonly OPHELDU = new ClientGameProt(169, 58, 12); // name based on runescript trigger

    static readonly INV_BUTTON1 = new ClientGameProt(190, 153, 6); // NXT has "IF_BUTTON1" but for our interface system, this makes more sense
    static readonly INV_BUTTON2 = new ClientGameProt(191, 193, 6); // NXT has "IF_BUTTON2" but for our interface system, this makes more sense
    static readonly INV_BUTTON3 = new ClientGameProt(192, 158, 6); // NXT has "IF_BUTTON3" but for our interface system, this makes more sense
    static readonly INV_BUTTON4 = new ClientGameProt(193, 204, 6); // NXT has "IF_BUTTON4" but for our interface system, this makes more sense
    static readonly INV_BUTTON5 = new ClientGameProt(194, 212, 6); // NXT has "IF_BUTTON5" but for our interface system, this makes more sense
    static readonly IF_BUTTON = new ClientGameProt(200, 39, 2); // NXT naming

    static readonly RESUME_PAUSEBUTTON = new ClientGameProt(201, 11, 2); // NXT naming
    static readonly CLOSE_MODAL = new ClientGameProt(202, 187, 0); // NXT naming
    static readonly RESUME_P_COUNTDIALOG = new ClientGameProt(203, 190, 4); // NXT naming
    static readonly TUTORIAL_CLICKSIDE = new ClientGameProt(204, 233, 1);

    static readonly MOVE_OPCLICK = new ClientGameProt(242, 167, -1); // comes with OP packets, name based on other MOVE packets
    static readonly REPORT_ABUSE = new ClientGameProt(243, 251, 10);
    static readonly MOVE_MINIMAPCLICK = new ClientGameProt(244, 56, -1); // NXT naming
    static readonly INV_BUTTOND = new ClientGameProt(245, 81, 7); // NXT has "IF_BUTTOND" but for our interface system, this makes more sense
    static readonly IGNORELIST_DEL = new ClientGameProt(246, 207, 8); // NXT naming
    static readonly IGNORELIST_ADD = new ClientGameProt(247, 203, 8); // NXT naming
    static readonly IF_PLAYERDESIGN = new ClientGameProt(248, 8, 13);
    static readonly CHAT_SETMODE = new ClientGameProt(249, 98, 3); // NXT naming
    static readonly MESSAGE_PRIVATE = new ClientGameProt(250, 170, -1); // NXT naming
    static readonly FRIENDLIST_DEL = new ClientGameProt(251, 69, 8); // NXT naming
    static readonly FRIENDLIST_ADD = new ClientGameProt(252, 9, 8); // NXT naming
    static readonly CLIENT_CHEAT = new ClientGameProt(253, 76, -1); // NXT naming
    static readonly MESSAGE_PUBLIC = new ClientGameProt(254, 171, -1); // NXT naming
    static readonly MOVE_GAMECLICK = new ClientGameProt(255, 63, -1); // NXT naming

    // in these old revisions we can actually get the packet index from a leftover array in the client source
    constructor(
        readonly index: number,
        readonly id: number,
        readonly length: number
    ) {
        ClientGameProt.all[index] = this;
        ClientGameProt.byId[id] = this;
    }
}
