export const enum ClientProt {
    NO_TIMEOUT = 107, // index: 6 - NXT naming

    IDLE_TIMER = 146, // index: 30

    EVENT_TRACKING = 217, // index: 34

    // autogenerated as part of obfuscation process
    ANTICHEAT_OPLOGIC1 = 47, // index: 60
    ANTICHEAT_OPLOGIC2 = 218, // index: 61
    ANTICHEAT_OPLOGIC3 = 37, // index: 62
    ANTICHEAT_OPLOGIC4 = 34, // index: 63
    ANTICHEAT_OPLOGIC5 = 7, // index: 64
    ANTICHEAT_OPLOGIC6 = 177, // index: 65
    ANTICHEAT_OPLOGIC7 = 50, // index: 66
    ANTICHEAT_OPLOGIC8 = 100, // index: 67
    ANTICHEAT_OPLOGIC9 = 169, // index: 68

    // autogenerated as part of obfuscation process
    ANTICHEAT_CYCLELOGIC1 = 46, // index: 70
    ANTICHEAT_CYCLELOGIC2 = 148, // index: 71
    ANTICHEAT_CYCLELOGIC3 = 144, // index: 74
    ANTICHEAT_CYCLELOGIC4 = 41, // index: 72
    ANTICHEAT_CYCLELOGIC5 = 232, // index: 75
    ANTICHEAT_CYCLELOGIC6 = 215, // index: 73

    OPOBJ1 = 231, // index: 80 - NXT naming
    OPOBJ2 = 110, // index: 81 - NXT naming
    OPOBJ3 = 27, // index: 82 - NXT naming
    OPOBJ4 = 17, // index: 83 - NXT naming
    OPOBJ5 = 225, // index: 84 - NXT naming
    OPOBJT = 25, // index: 88 - NXT naming
    OPOBJU = 111, // index: 89 - NXT naming

    OPNPC1 = 222, // index: 100 - NXT naming
    OPNPC2 = 84, // index: 101 - NXT naming
    OPNPC3 = 132, // index: 102 - NXT naming
    OPNPC4 = 229, // index: 103 - NXT naming
    OPNPC5 = 102, // index: 104 - NXT naming
    OPNPCT = 101, // index: 108 - NXT naming
    OPNPCU = 52, // index: 109 - NXT naming

    OPLOC1 = 238, // index: 120 - NXT naming
    OPLOC2 = 38, // index: 121 - NXT naming
    OPLOC3 = 19, // index: 122 - NXT naming
    OPLOC4 = 55, // index: 123 - NXT naming
    OPLOC5 = 243, // index: 124 - NXT naming
    OPLOCT = 182, // index: 128 - NXT naming
    OPLOCU = 106, // index: 129 - NXT naming

    OPPLAYER1 = 211, // index: 140 - NXT naming
    OPPLAYER2 = 219, // index: 141 - NXT naming
    OPPLAYER3 = 64, // index: 142 - NXT naming
    OPPLAYER4 = 43, // index: 143 - NXT naming
    OPPLAYERT = 73, // index: 148 - NXT naming
    OPPLAYERU = 48, // index: 149 - NXT naming

    OPHELD1 = 228, // index: 160 - name based on runescript trigger
    OPHELD2 = 166, // index: 161 - name based on runescript trigger
    OPHELD3 = 221, // index: 162 - name based on runescript trigger
    OPHELD4 = 6, // index: 163 - name based on runescript trigger
    OPHELD5 = 133, // index: 164 - name based on runescript trigger
    OPHELDT = 143, // index: 168 - name based on runescript trigger
    OPHELDU = 58, // index: 169 - name based on runescript trigger

    INV_BUTTON1 = 153, // index: 190 - NXT has "IF_BUTTON1" but for our interface system, this makes more sense
    INV_BUTTON2 = 193, // index: 191 - NXT has "IF_BUTTON2" but for our interface system, this makes more sense
    INV_BUTTON3 = 158, // index: 192 - NXT has "IF_BUTTON3" but for our interface system, this makes more sense
    INV_BUTTON4 = 204, // index: 193 - NXT has "IF_BUTTON4" but for our interface system, this makes more sense
    INV_BUTTON5 = 212, // index: 194 - NXT has "IF_BUTTON5" but for our interface system, this makes more sense
    IF_BUTTON = 39, // index: 200 - NXT naming

    RESUME_PAUSEBUTTON = 11, // index: 201 - NXT naming
    CLOSE_MODAL = 187, // index: 202 - NXT naming
    RESUME_P_COUNTDIALOG = 190, // index: 203 - NXT naming
    TUTORIAL_CLICKSIDE = 233, // index: 204

    MOVE_OPCLICK = 167, // index: 242 - comes with OP packets, name based on other MOVE packets
    REPORT_ABUSE = 251, // index: 243
    MOVE_MINIMAPCLICK = 56, // index: 244 - NXT naming
    INV_BUTTOND = 81, // index: 245 - NXT has "IF_BUTTOND" but for our interface system, this makes more sense
    IGNORELIST_DEL = 207, // index: 246 - NXT naming
    IGNORELIST_ADD = 203, // index: 247 - NXT naming
    IF_PLAYERDESIGN = 8, // index: 248
    CHAT_SETMODE = 98, // index: 249 - NXT naming
    MESSAGE_PRIVATE = 170, // index: 250 - NXT naming
    FRIENDLIST_DEL = 69, // index: 251 - NXT naming
    FRIENDLIST_ADD = 9, // index: 252 - NXT naming
    CLIENT_CHEAT = 76, // index: 253 - NXT naming
    MESSAGE_PUBLIC = 171, // index: 254 - NXT naming
    MOVE_GAMECLICK = 63, // index: 255 - NXT naming
};
